### ISSUE TITLE
Compatibility with ES r24

### ISSUE THREAD

**Issue by kusterjs** [LB767/vSMR#14]
The current release leads to a crash upon closing ES r24.

**Comment by LB767** [comment]
It works fine for me.
However there is a problem with the LSZH_test profile. You need to have `path ` and `path_rimcas` defined for it to work, only `path_lvp` is optional.
Let me know if that solves the problem by any chance...

**Comment by kusterjs** [comment]
No, still the same issue. Is there something else wrong with my json file?
[vSMR_Profiles.zip](https://github.com/LB767/vSMR/files/4527753/vSMR_Profiles.zip)

**Comment by LB767** [comment]
No it's all fine... does it output any error message when you close ES ?

**Comment by kusterjs** [comment]
No. Just freezes. We had that issue already when r23 was introduced. Maybe something similar? But it might also be something different according to the dicussions here: https://github.com/pierr3/vSMR/issues/55.

**Comment by pierr3** [comment]
Might have been fixed in my repo, give it a try

**Comment by kusterjs** [comment]
> Might have been fixed in my repo, give it a try

Appreciated, this should solve the issue from r24 onwards.

**Comment by LB767** [comment]
> 
> 
> Might have been fixed in my repo, give it a try

Merci !!
