### ISSUE TITLE
Different font sizes in label

### ISSUE THREAD

**Issue by kusterjs** [LB767/vSMR#2]
First line of the label should allowed to have a different (larger) font size than the remaining lines.
![image](https://user-images.githubusercontent.com/10661679/70382514-b9517e00-195d-11ea-997f-51a7775bacc9.png)

**Comment by LB767** [comment]
Right now there is a setting that allows you to change the font size of the whole tag.

![image](https://user-images.githubusercontent.com/20526358/70388924-a1f3ae80-19b8-11ea-9d9b-432044751f12.png)

Would you rather have it so the font sizes are fixed values you can set manually for the lines, or have a parameter to say "make the 1st line 1.2x the size of the normal size"?

Can't really do both at the same time as far as I can see.

**Comment by kusterjs** [comment]
I prefer a factor for the first line (2nd option).

**Comment by LB767** [comment]
Added in 1.4.2 (see latest release) let me know how it goes.

**Comment by kusterjs** [comment]
looks good! I would like to apply different factors for the main and the inset window (because the Zurich setting only has larger first lines in the main window, but not in the insets).

**Comment by LB767** [comment]
Is it ok if I just disable the scaling for the inset window? Or does Geneva need it? It would just be a lot easier code-wise not gonna lie :P

**Comment by kusterjs** [comment]
Geneva does no scaling of the first line at all, as far as I know. So disable it in general for the inset is fine.
