### ISSUE TITLE
Mouse symbol

### ISSUE THREAD

**Issue by kusterjs** [LB767/vSMR#5]
Mouse symbol should be reset to system default always when leaving a SMR view (so a custom defined symbol doesn't stay on default radar views). I would also make the cursor part of the settings that a controller can change in the plugin itself. So this would mean to move this from profiles to plugin settings.

**Comment by kusterjs** [comment]
This is quite annoying and I already had to explain this issue to other controllers (and that they won't be able to change the cursor symbol until they close ES). When leaving the vSMR view (also changing to a default ES radar view), the default cursor symbol as defined by the Windows settings should be set again.

**Comment by LB767** [comment]
Are you getting the custom cursor with `"cursor": "Default",` present in the profile file just to make sure? (If you add it just after the `"name": "LSZH_Ground",` line)

**Comment by kusterjs** [comment]
The problem is, it won't change when changing the profile. So this means whatever profile you used the last time, it will load this cursor and you cannot change in the entire ES session. Also, it should always be changed back when the asr view currently activated is not using vSMR.
Currently, the cursor symbol is decided when vSMR is loaded for the first time and it cannot be changed unless you re-launch ES.

**Comment by LB767** [comment]
Yes I know, but I wanted to make sure it was still showing the default cursor if you set it to default in the profile.
Anyway, I moved it to the menu bar settings now instead of the profile.json. However I could not find any non trivial way to have the cursor reset when the view changes, so we will just have to deal with using the normal Windows cursor for now.

**Comment by kusterjs** [comment]
There is no way to change it automatically to default always when/before changing to another asr view? Is there ne routine for this? Especially when controlling top-down, it would be nice to have the custom cursor in the vSMR view, but the normal one on the radar views.

**Comment by LB767** [comment]
Not that I could find... :(
If I remember correctly there is an event the plugin can detect when changing the ASR view from the ES menu, but not when using keyboard shortcuts...
It's really annoying and I'll keep looking for a solution but not much more I can do
