### ISSUE TITLE
ProMode

### ISSUE THREAD

**Issue by kusterjs** [LB767/vSMR#8]
ProMode settings and its associated subsettings should be taken from ES directly. It makes no sense to maintain f.e. two different lists of squawks.

**Comment by kusterjs** [comment]
I revoke my previous statement about the ProMode linked to the ES settings. It might be a good idea to have the vSMR ProMode running independently from the ES mode. So you can use vSMR in ProMode while you still run other instances of radar display in the easy mode.
But, for the autocorrelation (which I think is considered for ProMode only, correct me if I'm wrong), you can disregard all non-discrete squawks (those ending with 00) for the correlation. Such codes do not need to be excluded specifically from the correlation.

**Comment by kusterjs** [comment]
Are squawks to be not correlated from the default ES settings also considered?

**Comment by LB767** [comment]
> Are squawks to be not correlated from the default ES settings also considered?

As far as I know Euroscope does not provide plugins with this information so that's not possible.
In the profiles settings file you have a list of squawks to not autocorrelate
```
"do_not_autocorrelate_squawks": [
          "2000",
          "2200",
          "1200",
          "7000"
        ]
```
Can you elaborate what you meant by the codes ending with 00 being disregarded?

**Comment by kusterjs** [comment]
> Can you elaborate what you meant by the codes ending with 00 being disregarded?

if squawk mod 100 = 0, then do not autocorrelate
This is basically the rule which can be attributed to the ProMode without the need to define a list of squawks. So this setting could be withdrawn then as a result.

**Comment by LB767** [comment]
Oh ok, that's simple enough. I'll add it in directly in vSMR then. Cheers

**Comment by LB767** [comment]
Just noticed, but the exception to this rule is squawk 1000 correct? (for us anyway)

**Comment by kusterjs** [comment]
Yes, you are right.
